### Site Settings ###
title: Dan Ford
tagline: maps, design, software, conservation
description: Owner of Windrose Maps. Author and Illustrator of Map Projections for Babies. Conservationist passionate about land preservation.
image: /assets/images/meta.png
url: "http://www.danford.us"
subtitle: >-
          conservation | design | maps | technology
cta1_url: /blog
cta1_desc: Read my latest posts
cta2_url: /projects
cta2_desc: Check out my projects
baseurl: ""
repository: danford1/danford1.github.io

social:
  name: Dan Ford
  links:
  - https://twitter.com/danjford
  - https://www.linkedin.com/in/dan-ford-maps
  - https://github.com/danford1

### Plugins ###
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap


### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Dan Ford
  image             : /assets/images/dan.jpg
  linkedin          : dan-ford-maps
  instagram         : danjford
  twitter           : danjford
  github            : danford1
# behance           : your_username
# dribbble          : your_username
# email             : username@domain.com
# facebook          : your_username
# gitlab            : your_username
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# vimeo             : your_username
# youtube           : your_channel_name

### Analytics ###
analytics:
  enabled: true # Set true to enable analytics
  google:
    tracking_id: UA-171153643-1


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - vendor
